services:
  - type: web
    name: sistema-gestion-taller
    env: python
    repo: https://github.com/tu-usuario/sistema-gestion-taller
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.16
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: "False"
      - key: DATABASE_PATH
        value: "./taller.db"
    disk:
      name: sqlite-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
